In [3]:
import numpy as np


In [4]:
a = np.array([20,40,60])
b = np.array([10,20,30])
c = np.array([5, 10, 15, 20])

In [5]:
a+b

array([30, 60, 90])

In [6]:
a+c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [7]:
a-c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [8]:
a*b

array([ 200,  800, 1800])

In [9]:
a/b

array([2., 2., 2.])

In [11]:
scalar = 2
list_a=[10,11,12,13,14,15]
print(list_a)
list_as_array = np.array(list_a)
print(list_as_array)

[10, 11, 12, 13, 14, 15]
[10 11 12 13 14 15]


In [12]:
scalar*list_a

[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]

In [13]:
scalar*list_as_array

array([20, 22, 24, 26, 28, 30])